# =============================================
# PRODUCTION CONFIG — shopapp backend (Render)
# Tất cả ${...} sẽ đọc từ Environment Variables
# trên Render dashboard
# =============================================

# Database (Railway MySQL)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

jwt.expiration=${JWT_EXPIRATION:86400}
jwt.secretKey=${JWT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}

spring.vnpay.tmnCode=${VNPAY_TMN_CODE:placeholder}
spring.vnpay.hashSecret=${VNPAY_HASH_SECRET:placeholder}
spring.vnpay.url=${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
spring.vnpay.returnUrl=${VNPAY_RETURN_URL:https://localhost:4200/orders}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

api.prefix=/api/v1


server.port=${PORT:8088}